### ISSUE TITLE
Capstone Project Setup

### ISSUE THREAD

**Issue by gjuliao** [Oscar-Espinoza/pokedex#21]
- [Github Capstone Project- Team of 2](https://github.com/Oscar-Espinoza/pokedex/projects/1)

## Collaborators
@Oscar-Espinoza @gjuliao

**Comment by julie-ify** [comment]
Hi @gjuliao and @Oscar-Espinoza,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the project, instead of your repository

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by julie-ify** [comment]
## Hi @gjuliao and @Oscar-Espinoza,

Good job so far!

## Highlights!
- Descriptive pull request ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] All your group tasks are assigned to no one. Kindly assign the tasks among yourselves evenly, or to both of you.

  ![djduoep](https://user-images.githubusercontent.com/81468675/210259523-62a3e558-7fc1-4f5e-a56f-acce83f26b9e.jpg)

- [ ] This task is not assigned to anyone. Kindly fix that.

  ![image](https://user-images.githubusercontent.com/81468675/210259510-0f020aba-89c0-41da-b62b-73710b45a09e.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
# 🟢 STATUS: APPROVED 🟢

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

Cheers and Happy coding!👏👏👏

Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
